#ifndef CONFIG
#define CONFIG

#define LIGHT_SENSOR_PIN A0

#define INTERIOR_ULTRASONIC_SENSOR_TRIG_PIN 17
#define INTERIOR_ULTRASONIC_SENSOR_ECHO_PIN 18
#define INTERIOR_ULTRASONIC_SENSOR_MAX_DISTANCE 10

#define EXTERIOR_ULTRASONIC_SENSOR_TRIG_PIN 10
#define EXTERIOR_ULTRASONIC_SENSOR_ECHO_PIN 10
#define EXTERIOR_ULTRASONIC_SENSOR_MAX_DISTANCE 10

#define LIGHT_BULT_PIN 4

#endif